<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class Eden_Oauth_Tests_Paypal_FactoryTest extends \PHPUnit_Framework_TestCase
{
    public function testAuthorization()
    {
		$authorization = eden('paypal')->authorization('user', 'password', 'signature', 'certificate');
        $this->assertInstanceOf('Eden\\Paypal\\Authorization', $authorization);
    }

    public function testBilling()
    {
        $billing = eden('paypal')->billing('user', 'password', 'signature', 'certificate');
        $this->assertInstanceOf('Eden\\Paypal\\Billing', $billing);
    }

    public function testButton()
    {
        $button = eden('paypal')->button('user', 'password', 'signature', 'certificate');
        $this->assertInstanceOf('Eden\\Paypal\\Button', $button);
    }

    public function testCheckout()
    {
        $checkout = eden('paypal')->checkout('user', 'password', 'signature', 'certificate');
        $this->assertInstanceOf('Eden\\Paypal\\Checkout', $checkout);
    }

    // public function testDirect()
    // {
    //     $object = eden('paypal')->direct('user', 'password', 'signature', 'certificate');
    //     print_r($object);
    //     $this->assertInstanceOf('Eden\\Paypal\\Direct', $object);
    // }

    public function testRecurring()
    {
        $object = eden('paypal')->recurring('user', 'password', 'signature', 'certificate');
        $this->assertInstanceOf('Eden\\Paypal\\Recurring', $object);
    }

    public function testTransaction()
    {
        $object = eden('paypal')->transaction('user', 'password', 'signature', 'certificate');
        $this->assertInstanceOf('Eden\\Paypal\\Transaction', $object);
    }

}