<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class Eden_Oauth_Tests_Paypal_AuthorizationTest extends \PHPUnit_Framework_TestCase
{
    public function testDoAuthorization()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->doAuthorization();
        // print_r($obj);
    }

    public function testDoAuthorizationoCapture()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->doCapture();
        //print_r($obj);
    }

    public function testDoReAuthorization()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->doReAuthorization();
        //print_r($obj);
    }

    public function testDoVoid()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->doVoid();
        //print_r($obj);
    }

    public function testSetAmount()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->setAmount(100);
        //print_r($obj);
    }

    public function testSetComplete()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->setComplete();
        //print_r($obj);
    }

    public function testSetCurrency()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->setCurrency('currency');
        //print_r($obj);
    }

    public function testSetNoComplete()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->setNoComplete();
        //print_r($obj);
    }

    public function testSetNote()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->setNote('note');
        //print_r($obj);
    }

    public function testSetTransactionId()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->setTransactionId('id');
        //print_r($obj);
    }
}