<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class Eden_Oauth_Tests_Paypal_BillingTest extends \PHPUnit_Framework_TestCase
{
    public function testDoAuthorization()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->doAuthorization();
        // print_r($obj);
    }

}