<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class Eden_Oauth_Tests_Paypal_BillingTest extends \PHPUnit_Framework_TestCase
{
    public function testDoAuthorization()
    {
        $obj = eden('paypal')->authorization('user', 'password', 'signature', 'certificate')->doAuthorization();
        // print_r($obj);
    }

}<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class Eden_Oauth_Tests_Paypal_BillingTest extends \PHPUnit_Framework_TestCase
{
    public function testBilling()
    {
        $obj = eden('paypal')->billing('user', 'password', 'signature', 'certificate')->billing('return', 'cancel');
        // print_r($obj);
    }

    public function testAgreementCustom()
    {
        $obj = eden('paypal')->billing('user', 'password', 'signature', 'certificate')->setAgreementCustom('agreementCustom');
        // print_r($obj);
    }

    public function testSetBillingDesc()
    {
        $obj = eden('paypal')->billing('user', 'password', 'signature', 'certificate')->setBillingDesc('billingDesc');
        // print_r($obj);
    }

    public function testSetBillingType()
    {
        $obj = eden('paypal')->billing('user', 'password', 'signature', 'certificate')->setBillingType('billingType');
        // print_r($obj);
    }

    public function testSetToAny()
    {
        $obj = eden('paypal')->billing('user', 'password', 'signature', 'certificate')->setToAny();
        // print_r($obj);
    }

    public function testSetToInstantOnly()
    {
        $obj = eden('paypal')->billing('user', 'password', 'signature', 'certificate')->setToInstantOnly();
        // print_r($obj);
    }

}