<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-20 at 08:38:01.
 */
class Eden_Oauth_Tests_Paypal_ButtonTest extends \PHPUnit_Framework_TestCase
{
    public function testGetButton()
    {
        $obj = eden('paypal')->button('user', 'password', 'signature', 'certificate')->getButton();
        // print_r($obj);
    }

}